/*
===========================================================================================
 
                                Copyright(c) 2000 - 2006 by

                       V o z z W a r e   L L C (Vw)

                                   All Rights Reserved

  THIS PROGRAM IS PROVIDED UNDER THE TERMS OF THE Vozzware LLC PUBLIC LICENSE VER 1.0 (�AGREEMENT�),
  PROVIDED WITH THIS PROGRAM. ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM
  CONSTITUTES RECEIPIENTS ACCEPTANCE OF THIS AGREEMENT.

  Source Name: VwORMDescriptor.java

  Create Date: Mar 22, 2005
============================================================================================
*/
package com.vozzware.db;

public class VwORMDescriptor
{
  /**
   * Constant for the save operation type
   */
  public final static int SAVE = 1;

  /**
   * Constant for the delete operation type
   */
  public final static int DEL = 2;
  
  public final static int OMIT = 1;
  
  public final static int CREATE_UUID = 2;
  
  public final static int CREATE_LONG = 3;
  
  private	String			m_strPrimeKeyCol;		// Name of the primary key getter method
  
  private VwSqlData	m_sqldInsert;				// Insert sql data
  private VwSqlData	m_sqldUpdate;			  // update sql data
  private VwSqlData	m_sqldDelete;			  // delete sql data
  
  private int					m_nOperationType;
  private int         m_nPrimeKeyPolicy; 	// if true, the primary key is autogenerated from database
  
  /**
   * @return Returns the nOperationType.
   */
  public int geOperationType()
  { return m_nOperationType; }
  
  
  /**
   * @param operationType The nOperationType to set.
   */
  public void setOperationType( int nOperationType )
  { m_nOperationType = nOperationType; }
  
  
  /**
   * @return Returns the sqldInsert.
   */
  public VwSqlData getInsert()
  { return m_sqldInsert; }
  
  
  /**
   * @param sqldInsert The sqldInsert to set.
   */
  public void setInsert( VwSqlData sqldInsert )
  { m_sqldInsert = sqldInsert; }
  
  
  /**
   * @return Returns the sqldUpdate.
   */
  public VwSqlData getUpdate()
  { return m_sqldUpdate; }
  
  
  /**
   * @param sqldUpdate The sqldUpdate to set.
   */
  public void setUpdate( VwSqlData sqldUpdate )
  {  m_sqldUpdate = sqldUpdate; }
  
  
  /**
   * @return Returns the strPrimeKeyCol.
   */
  public String getPrimeKeyCol()
  { return m_strPrimeKeyCol; }
  
  
  /**
   * @param strPrimeKeyCol The strPrimeKeyCol to set.
   */
  public void setPrimeKeyCol( String strPrimeKeyCol )
  { m_strPrimeKeyCol = strPrimeKeyCol; }
  
  
  
  /**
   * Gets the primary key action behaviour constant for insert operations
   * 
   * @return Returns the nPrimeKeyOnInserts.
   */
  public int getPrimeKeyPolicy()
  {
    return m_nPrimeKeyPolicy;
  }
  
  
  /**
   * Sets the primary key action behaviour constant for insert operations
   * 
   * @param primeKeyOnInserts The nPrimeKeyOnInserts to set.
   */
  public void setPrimePolicy( int nPrimeKeyPolicy )
  {
    m_nPrimeKeyPolicy = nPrimeKeyPolicy;
  }
} // end class VwORMDescriptor{}

// *** End of VwORMDescriptor.java ***

